name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u cloudbench1 --password-stdin

    - name: Build Docker Image
      run: docker build . --tag ghcr.io/cloudbench1/action:${{ github.sha }}

    - name: Push Docker Image
      run: docker push ghcr.io/cloudbench1/action:${{ github.sha }}


   

