name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Trigger for version tags like v1.0.0
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker Image
      run: |
        IMAGE_TAG=ghcr.io/cloudbench1/simplenodeapp:${{ github.sha }}
        
        # Check if a version tag is present
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION_TAG="ghcr.io/cloudbench1/simplenodeapp:${GITHUB_REF#refs/tags/}"
          docker build . --tag $IMAGE_TAG --tag $VERSION_TAG
        else
          docker build . --tag $IMAGE_TAG
        fi

    - name: Push Docker Image
      run: |
        IMAGE_TAG=ghcr.io/cloudbench1/simplenodeapp:${{ github.sha }}
        
        # Push the main image
        docker push $IMAGE_TAG
        
        # If a version tag is present, push that as well
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION_TAG="ghcr.io/cloudbench1/simplenodeapp:${GITHUB_REF#refs/tags/}"
          docker push $VERSION_TAG
        fi

    - name: Notify via Email on Success
      if: success()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Docker Build Success - SimpleNodeApp"
        to: "cloudbench3@gmail.com"
        from: "GitHub Actions"
        body: "The Docker image for SimpleNodeApp has been successfully built and pushed to GitHub Packages."

