name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker Image
      run: |
        IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ github.sha }}
        
        
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION_TAG="ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}"
          docker build . --tag $IMAGE_TAG --tag $VERSION_TAG
        else
          docker build . --tag $IMAGE_TAG
        fi

    - name: Push Docker Image
      run: |
        IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ github.sha }}
        
       
        docker push $IMAGE_TAG
        
        
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          VERSION_TAG="ghcr.io/${{ github.repository }}:${GITHUB_REF#refs/tags/}"
          docker push $VERSION_TAG
        fi

