name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u mert2m --password-stdin

    - name: Build Docker Image
      run: docker build . --tag ghcr.io/mert2m/action:${{ github.sha }}

    - name: Push Docker Image
      run: docker push ghcr.io/mert2m/action:${{ github.sha }}

  notify:
    runs-on: ubuntu-latest
    needs: build  

    steps:
    - name: Send Notification via Email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PASS }}
        subject: "✅ Docker Build Completed!"
        body: "The Docker image has been successfully built and pushed to GHCR.\nImage: ghcr.io/mert2m/action:${{ github.sha }}"
        to: ${{ secrets.NOTIFY_EMAIL }}
        from: "GitHub Actions"

  
